### ISSUE TITLE
DX: pdo driver options

### ISSUE THREAD

**Issue by staabm** [Smile-SA/gdpr-dump#112]
### Preconditions

GdprDump Version: 4.1.1

PHP Version: PHP 8.2.12

Database Version: mysql 8

### Steps to reproduce

to properly connect to our database server we need a encrypted PDO connection, which needs to be achivied via PDO driver options.

such options in our use-case look like 

```
[
            \PDO::MYSQL_ATTR_SSL_CA => __DIR__.'/ca-cert.pem',
            \PDO::MYSQL_ATTR_SSL_KEY => __DIR__.'/client-key.pem',
            \PDO::MYSQL_ATTR_SSL_CERT => __DIR__.'/client-cert.pem',
            \PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => 'false',
]
```

### Expected result

I think it would be helpful to allow passing driver options from config.yml, in a similar way the host/user/password/db-name are configurable

### Actual result

it seems there is currently no way to set driver options, if I did not miss anything

**Comment by guvra** [comment]
Hi,

cf. `driver_options` setting in the wiki.
PHP constants are not available in the yaml file, but IIRC it's possible to use integer values instead as the object keys (the value of the constants).

**Comment by staabm** [comment]
ahh right thank you. it works like

```
database:
    host: '...'
    user: '..'
    password: 'my-pw'
    name: 'db-name'
    driver_options:
        1007: "/www/www/gdpr-dump/client-key.pem" # PDO::MYSQL_ATTR_SSL_KEY
        1008: "/www/www/gdpr-dump/client-cert.pem" # PDO::MYSQL_ATTR_SSL_CERT
        1009: "/www/www/gdpr-dump/ca-cert.pem" # PDO::MYSQL_ATTR_SSL_CA
        1014: "false" # PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
```

I mixed it up with `driverOptions` which did not exist and failed :)
