### ISSUE TITLE
DX: validate `columns` in tables config

### ISSUE THREAD

**Issue by bloep** [Smile-SA/gdpr-dump#124]
**Is your feature request related to a problem? Please describe.**
I am writing a config for over 250 database tables, each with more than 10 columns.
After I have created the config and generated a test dump (which takes 15 minutes due to the size of the database), I check it.
Columns were not changed because I had typos in the names e.g. `address` vs `address`.

**Describe the solution you'd like**
Before it starts exporting the data, it would be good to validate the config once against the schema to see if all columns are really there.

**Comment by guvra** [comment]
Implemented in #125 but all existing templates in app/config/templates must be tested before merging.

**Comment by guvra** [comment]
FYI, it's a breaking change, so it will be included in the 5.0.0 release.

**Comment by bloep** [comment]
Thanks for implementing it. IMHO we can close the issue
