### ISSUE TITLE
Timezone variable

### ISSUE THREAD

**Issue by Olivier-Vromans** [Smile-SA/gdpr-dump#133]
**Is your feature request related to a problem? Please describe.**
When I dump my database I like to have it use the current time but when I do it isn't in my timezone.

**Describe the solution you'd like**
I would appreciate it when there is an option within the dump setting in the config file, that allows you to change the timezone in date of the filename.  I have now hardcoded this line in `src/Config/Compiler/Processor/DumpOutputProcessor.php`. and than compiled it again and that works fine

```
date_default_timezone_set('Europe/Amsterdam');
```

**Describe alternatives you've considered**
It can also be an hardcoded time zone that is possible to change when you compile it on your own, how I did it.

**Comment by guvra** [comment]
It is already possible to do so with the php command line:

```
php -d date.timezone=UTC gdpr-dump.phar mydb.yaml
```

**Comment by Olivier-Vromans** [comment]
Ooh great thanx, this works. I was also wondering if there is a place to ask questions about the config file?
