### ISSUE TITLE
The table "email_order" uses a converter on an undefined column "email_imported".

### ISSUE THREAD

**Issue by lohoy** [Smile-SA/gdpr-dump#140]
We have an issue with Smile GdprDump v5.0.0
`The table "email_order" uses a converter on an undefined column "email_imported".`
https://github.com/Smile-SA/gdpr-dump/blob/e4ad92b835488c37f4a83cf33b2e64cec85d014c/app/config/templates/magento2.yaml#L597

**Comment by guvra** [comment]
Thanks for the report, this is fixed by #141 and is included in the 5.0.1 release.
