### ISSUE TITLE
php 7.2 compatibility

### ISSUE THREAD

**Issue by dooblem** [Smile-SA/gdpr-dump#40]
Hello,

Thanks for the tool. We have tested it and it's really great at anonymising magento2.

For a project (hosted by smile hosting !). We currently only have a php 7.2 at disposal.

Is the php7.3 requirement hard ?

It would be great if we can run it on php 7.2

Thanks in advance,
Marc

**Comment by guvra** [comment]
Hi,

> Thanks for the tool. We have tested it and it's really great at anonymising magento2.

I'm glad to hear that :smiley: 

> Is the php7.3 requirement hard ?

No, you can use version 1.2.3, which is compatible with PHP >= 7.0.
If you look at the changelog, you will notice that there are not a lot of difference with the most recent versions.

Warning: some converters were renamed in version 2.1.0, so use the appropriate tag to browse the documentation:
https://github.com/Smile-SA/gdpr-dump/blob/1.2.3/docs
