### ISSUE TITLE
Manage tables prefix

### ISSUE THREAD

**Issue by adrienmornet** [Smile-SA/gdpr-dump#41]
Hi there,

Thank's for this handy tool !

I think it can be a good idea to manage tables prefix as magento can use them, it will allow users to don't have to override your template anonymization rules.

Best,
Adrien.

**Comment by guvra** [comment]
There are multiple params that really on table names:

- `tables_blacklist`
- `tables_whitelist`
- `tables`
- `variables`

The param `variables` contains hardcoded SQL queries, so it would be pretty complex to automatically add a prefix to these queries.

IMO in your use case it's more simple to just copy the template that you want to use (eg. magento.yaml), replace table names, and use it as the template file.

PS: prefixing table names in magento is unnecessary if you do not use a shared database.
cf. https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-install.html#instgde-install-cli-magento
