### ISSUE TITLE
Define and use default config name

### ISSUE THREAD

**Issue by amenk** [Smile-SA/gdpr-dump#44]
**Is your feature request related to a problem? Please describe.**

Automatically read a default config in the current folder

**Describe the solution you'd like**

It would be nice to be able to omit the config file parameter and commit the configuration file to the project under a well-known name such as .gdpr-dump.yml

**Describe alternatives you've considered**

Just call gdpr-dump.phar .gdpr-dump.yml

**Comment by guvra** [comment]
I'm not convinced that it would be useful.

There are two main differences with tools like phpcs/phpstan:

- phpcs/phpstan are usually installed as a composer package within the project (in the vendor folder). We recommend using gdpr-dump as a standalone app (more secure / less risks of package conflicts).
- phpcs/phpstan are used on a regular basis. You rarely have to use gdpr-dump once your project is setup.

> Just call gdpr-dump.phar .gdpr-dump.yml

It is what I would do (except i would use the ".yaml" extension :smiley:)
