### ISSUE TITLE
Let's specify the database credentials on the command line

### ISSUE THREAD

**Issue by amenk** [Smile-SA/gdpr-dump#45]
**Is your feature request related to a problem? Please describe.**

It would be good if we can commit the dump config to the git repo, but don't have to put the db credentials

**Describe the solution you'd like**

accept the same parameters like mysql-dump does for the connection info (`-h host -u user --password=foobar dbname`)

**Comment by guvra** [comment]
It is already possible to hide the credentials, you have to use [environment variables](https://github.com/Smile-SA/gdpr-dump/blob/master/docs/01-configuration.md#user-content-environment-variables).

I'll update the guidelines, it's not specified currently.

**Comment by amenk** [comment]
Ah okay, thanks. That would need some boilerplate like

    database:
        host: '%env(DATABASE_HOST)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        name: '%env(DATABASE_NAME)%'

Or does it work by default?

Both is okay though ...

**Comment by guvra** [comment]
Yes, any value in the configuration file can be associated to an environment variable.

I updated the guidelines: https://github.com/Smile-SA/gdpr-dump/blob/f53b4b099e3f7a73940185ce1d71e1b1335ca434/docs/03-guidelines.md#security

There are also multiple examples:

- https://github.com/Smile-SA/gdpr-dump/blob/f53b4b099e3f7a73940185ce1d71e1b1335ca434/app/config/example.yaml
- https://github.com/Smile-SA/gdpr-dump/blob/f53b4b099e3f7a73940185ce1d71e1b1335ca434/tests/functional/Resources/config/templates/test.yaml
