### ISSUE TITLE
Add template for moodle LMS

### ISSUE THREAD

**Issue by amenk** [Smile-SA/gdpr-dump#46]
**Is your feature request related to a problem? Please describe.**
Moodle is not supported yet out of the box

**Describe the solution you'd like**

We can contribute a template I guess, if it is not yet existing somewhere :)

**Comment by guvra** [comment]
We don't aim to provide a default file for every framework available, that would be too complex to maintain.

It's possible to add new templates manually:

1. Add the file to the folder "app/config/templates"
2. Run the compiler:
    ```
    composer install
    php -d phar.readonly=off bin/compile
    ```
3. The phar is generated in the folder "build/dist".

This will create a file named "gdpr-dump.phar" in the folder "build/dist".

Compiling a custom phar also allows you to add custom converters / additional faker translations.

A plugin system would be nice to have but not planned at the moment.

**Comment by amenk** [comment]
That's a pity then :-( It thought that is the idea of the project - but I understand that it's not so easy to maintain.
But how is decided that magento1 + 2 + oro is part of the project but not others, hm..

thanks anyways for the compile instructions.

A simple plugin system would be cool.
