### ISSUE TITLE
Write errors to STDERR

### ISSUE THREAD

**Issue by amenk** [Smile-SA/gdpr-dump#47]
### Preconditions

Have an invalid yaml file

GdprDump Version: 2.1.1

### Steps to reproduce
1. Execute gdpr-dump config.yaml > gdprdump.sql

### Expected result
1. An error message is shown on the console

### Actual result
1. No error message is shown, but the error message can be found in the gdprdump.sql file

**Comment by guvra** [comment]
Thanks for the report, the PR #49 fixes this issue.

Warning: stderr is disabled by default, you must set `display_errors` to `stderr` to enable it.

**Comment by amenk** [comment]
@guvra thank you, that was quick.
But why not enabled it by default?

**Comment by guvra** [comment]
@amenk My bad, after additional testing, I can confirm it works regardless of the value of display_errors :smiley:
