### ISSUE TITLE
Add a scan command to identify potential PII columns

### ISSUE THREAD

**Issue by peterjaap** [Smile-SA/gdpr-dump#91]
**Is your feature request related to a problem? Please describe.**
When implementing this in a project, I'd like to have a tool that scans the database for me and lists columns that potentially hold personally identifiable data.

**Describe the solution you'd like**
A scan console command that outputs a list.

**Describe alternatives you've considered**
We used this in our own tool https://github.com/elgentos/masquerade and it was really useful

**Additional context**
I built this and PR'd this here; https://github.com/Smile-SA/gdpr-dump/pull/90

When this is merged and working, the next step would be to add a `--generate-whitelist` option that adds all remaining output into a whitelist. That way, I can hook up the scan command in a pipeline which can fail or notify me through Slack when a new column has been added and potentially needs to be configured in gdpr-dump.

**Comment by guvra** [comment]
Hello @peterjaap ,

Couldn't you implement this in a separate application?

You could add gdpr-dump as a composer dependency in order to use the config loader to scan the config file.

**Comment by peterjaap** [comment]
@guvra i van, but is there a specific reason why it can’t be merged into the main application?

**Comment by guvra** [comment]
It would require a lot of work to implement it properly and i'm not even sure we would use it.

Examples of issues of the PR:

- It's very focused on magento (this tool is framework agnostic).
- There are a hardcoded strings (e.g. if column name contains `x` then suggest converter `y`).
- There is duplicated code with the dump command.
- Our tool is currently designed as a single-command application, with the current PR it isn't possible to launch the scan command from the phar file.
